# 上下文初始化加载
info:
  name: Eureka server
  contact: 注册中心
  
management:
  security:
    enabled: false
    
spring:
  profiles:
    active: dev

#profile数组 ---
---
spring:
  profiles: dev
server:
  port: 8761
eureka:
  #作为客户端(每个服都可以看作消费端和服务端)
  client:
    # 是否注册到eurekaserver
    registerWithEureka: true
    # 是否拉注册取信息
    fetchRegistry: false
    # eureka server地址
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    # false 关闭自我保护，不管如何都要剔除心跳检测异常的服务
    enableSelfPreservation: false
    #服务踢除时间(默认60000ms)
    eviction-interval-timer-in-ms: 60000
    #eureka 集群刷新间隔
    peer-eureka-nodes-update-interval-ms: 10000
  instance:
    hostname: eureka1
    #实例心跳时间(默认30s)
    lease-renewal-interval-in-seconds: 30
    #超过上次心跳30s 认为宕机(默认90s)
    lease-expiration-duration-in-seconds: 30
---
spring:
  profiles: prod2
server:
  port: 8763
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eureka_serviceUrl:http://127.0.0.1:8761/eureka/}
  server:
    waitTimeInMsWhenSyncEmpty: 0
    # false 关闭自我保护，不管如何都要剔除心跳检测异常的服务
    enableSelfPreservation: false
    # 服务剔除任务执行周期
    evictionIntervalTimerInMs: 60000
    # 服务端缓存最长时间
    responseCacheUpdateIntervalMs: 30000
  instance:
    hostname: eureka2